
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

const cleanReportContent = (content: string): string => {
  // Remove unwanted sections
  let cleaned = content;
  
  // Remove the "Would you like me to email this report..." section
  cleaned = cleaned.replace(/Would you like me to email this report.*?Session ID:.*$/gims, '');
  
  // Remove session ID references
  cleaned = cleaned.replace(/Session ID:.*$/gm, '');
  
  // Remove "Generated by FlowSense Care Intelligence System" if standalone
  cleaned = cleaned.replace(/^\s*Generated by FlowSense Care Intelligence System\s*$/gm, '');
  
  // Remove email formatting instructions
  cleaned = cleaned.replace(/EMAIL_TO:.*?---/gims, '');
  
  // Clean up extra whitespace
  cleaned = cleaned.replace(/\n\s*\n\s*\n/g, '\n\n');
  cleaned = cleaned.trim();
  
  return cleaned;
};

const formatContentAsHTML = (content: string): string => {
  // Clean the content first
  const cleanedContent = cleanReportContent(content);
  
  // Convert text to HTML with proper formatting
  let html = cleanedContent
    // Convert headers (lines that end with :)
    .replace(/^([A-Z][A-Za-z\s]+:)\s*$/gm, '<h3 style="color: #1e40af; margin: 20px 0 10px 0; font-weight: bold;">$1</h3>')
    
    // Convert bullet points
    .replace(/^[-•*]\s+(.+)$/gm, '<li style="margin: 5px 0;">$1</li>')
    
    // Wrap consecutive list items in ul tags
    .replace(/(<li[^>]*>.*<\/li>\s*)+/gs, '<ul style="margin: 10px 0; padding-left: 20px;">$&</ul>')
    
    // Convert numbered lists
    .replace(/^\d+\.\s+(.+)$/gm, '<li style="margin: 5px 0;">$1</li>')
    
    // Convert paragraphs (lines that don't start with < and aren't empty)
    .replace(/^(?!<|$)(.+)$/gm, '<p style="margin: 10px 0; line-height: 1.6;">$1</p>');
  
  return html;
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { to_email, subject, message_content } = await req.json();

    console.log('High priority report email request:', {
      to_email,
      subject: subject?.substring(0, 50),
      message_length: message_content?.length
    });

    if (!to_email || !subject || !message_content) {
      throw new Error('Missing required fields: to_email, subject, message_content');
    }

    const RESEND_API_KEY = Deno.env.get("RESEND_API_KEY");
    if (!RESEND_API_KEY) {
      throw new Error('Resend API key not configured');
    }

    // Format the content as HTML
    const formattedContent = formatContentAsHTML(message_content);
    
    // Get current date in a readable format
    const reportDate = new Date().toLocaleString('en-US', {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
      timeZoneName: 'short'
    });

    const response = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${RESEND_API_KEY}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        from: 'FlowSense Care <onboarding@resend.dev>',
        to: [to_email],
        subject: subject,
        html: `
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>${subject}</title>
          </head>
          <body style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; color: #333; margin: 0; padding: 0; background-color: #f8fafc;">
            <div style="max-width: 800px; margin: 0 auto; background-color: white; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);">
              
              <!-- Header -->
              <div style="background: linear-gradient(135deg, #1e40af 0%, #3b82f6 100%); color: white; padding: 30px; text-align: center;">
                <h1 style="margin: 0; font-size: 28px; font-weight: bold;">🏥 FlowSense Care</h1>
                <p style="margin: 10px 0 0 0; font-size: 16px; opacity: 0.9;">Healthcare Intelligence Report</p>
              </div>
              
              <!-- Content -->
              <div style="padding: 40px;">
                <div style="border-left: 4px solid #3b82f6; padding-left: 20px; margin-bottom: 30px;">
                  <h2 style="color: #1e40af; margin: 0 0 10px 0; font-size: 24px;">${subject}</h2>
                  <p style="color: #6b7280; margin: 0; font-size: 14px;">Generated on ${reportDate}</p>
                </div>
                
                <div style="background-color: #f8fafc; padding: 30px; border-radius: 8px; border: 1px solid #e5e7eb;">
                  ${formattedContent}
                </div>
              </div>
              
              <!-- Footer -->
              <div style="background-color: #f3f4f6; padding: 20px; text-align: center; border-top: 1px solid #e5e7eb;">
                <p style="margin: 0; color: #6b7280; font-size: 12px;">
                  This report was automatically generated by FlowSense Care Intelligence System
                </p>
                <p style="margin: 5px 0 0 0; color: #9ca3af; font-size: 11px;">
                  © ${new Date().getFullYear()} FlowSense Care - Healthcare Analytics Platform
                </p>
              </div>
              
            </div>
          </body>
          </html>
        `
      })
    });

    const result = await response.json();

    if (response.ok) {
      console.log('Email sent successfully:', {
        messageId: result.id,
        to_email
      });

      return new Response(JSON.stringify({
        success: true,
        messageId: result.id,
        to_email,
        subject,
        deliveredAt: new Date().toISOString()
      }), {
        status: 200,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      });
    } else {
      throw new Error(`Resend API error: ${JSON.stringify(result)}`);
    }

  } catch (error) {
    console.error('Error sending high priority report email:', error);
    
    return new Response(JSON.stringify({
      success: false,
      error: 'Failed to send email',
      details: error.message
    }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' }
    });
  }
});
