
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { to_email, subject, message_content } = await req.json();

    console.log('High priority report email request:', {
      to_email,
      subject: subject?.substring(0, 50),
      message_length: message_content?.length
    });

    if (!to_email || !subject || !message_content) {
      throw new Error('Missing required fields: to_email, subject, message_content');
    }

    const RESEND_API_KEY = Deno.env.get("RESEND_API_KEY");
    if (!RESEND_API_KEY) {
      throw new Error('Resend API key not configured');
    }

    const response = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${RESEND_API_KEY}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        from: 'FlowSense Care <onboarding@resend.dev>',
        to: [to_email],
        subject: subject,
        html: `
          <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
            <h2 style="color: #2563eb;">FlowSense Care Intelligence Report</h2>
            <div style="background: #f8fafc; padding: 20px; border-radius: 8px; margin: 20px 0;">
              <pre style="white-space: pre-wrap; font-family: inherit;">${message_content}</pre>
            </div>
            <p style="color: #64748b; font-size: 14px;">
              Generated by FlowSense Care Intelligence System<br>
              Timestamp: ${new Date().toLocaleString()}
            </p>
          </div>
        `
      })
    });

    const result = await response.json();

    if (response.ok) {
      console.log('Email sent successfully:', {
        messageId: result.id,
        to_email
      });

      return new Response(JSON.stringify({
        success: true,
        messageId: result.id,
        to_email,
        subject,
        deliveredAt: new Date().toISOString()
      }), {
        status: 200,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      });
    } else {
      throw new Error(`Resend API error: ${JSON.stringify(result)}`);
    }

  } catch (error) {
    console.error('Error sending high priority report email:', error);
    
    return new Response(JSON.stringify({
      success: false,
      error: 'Failed to send email',
      details: error.message
    }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' }
    });
  }
});
