// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fnmhdaxnlumkxtrtlvgc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZubWhkYXhubHVta3h0cnRsdmdjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NzEyNjksImV4cCI6MjA2NDA0NzI2OX0.jcJ7eeWQjCifWpak4EkdpqeSvFtcIiM-VRWDKMUh3bI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);